before_build:
  - where tar
  - ps: Start-FileDownload 'http://mirror.ctan.org/systems/texlive/tlnet/install-tl.zip'
  - 7z x install-tl.zip
  - cd install-tl-20*
  - ps: Set-Content texlive.profile "selected_scheme scheme-minimal`nTEXDIR C:\texlive`noption_doc 0`noption_src 0`n"

build_script:
  - echo | install-tl-windows.bat -v -profile=texlive.profile
  - set PATH=%PATH%;C:\texlive\bin\win32

test_script:
  - tlmgr --version
