before_build:
  - echo "TEXDIR C:\texlive" >> texlive.profile

build_script:
  - echo | install-tl-windows.bat -v -profile=texlive.profile
  - set PATH=%PATH%;C:\texlive\bin\win32

test_script:
  - tlmgr --version
